[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.dev]
debug = false

[profile.release]
lto = "thin"

[alias]
in = "binstall"

[build]
rustc-wrapper = "cachepot"
