[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.dev]
debug = false

[profile.release]
lto = "thin"

[build]
target-dir = "/home/yxqsnz/.cargo/target"
rustc-wrapper = "sccache"
